"""api.py — Flask API for real-time chat ingestion and hallucination detection."""

from __future__ import annotations

import os
from flask import Flask, request, jsonify
from typing import Dict, Any

from real_time_processor import process_single_chat
from chat_database import ChatDatabase
from chat_simulator import ChatSimulator

app = Flask(__name__)

DB_PATH = os.environ.get("CHAT_DB_PATH", "chat_database.db")


def next_chat_id(db_path: str) -> int:
    with ChatDatabase(db_path) as db:
        stats = db.stats()
        return stats["total_chats"] + 1


@app.route("/health", methods=["GET"])
def health() -> Any:
    return jsonify({"status": "ok", "db_path": DB_PATH})


@app.route("/chat", methods=["POST"])
def process_chat_route() -> Any:
    """Process a chat payload through the real-time processor."""
    payload = request.get_json(force=True)
    if payload is None:
        return jsonify({"error": "JSON payload required"}), 400

    messages = payload.get("messages")
    issue_type = payload.get("issue_type")
    persona = payload.get("persona", "standard")
    dry_run = payload.get("dry_run", False)
    chat_id = payload.get("chat_id")

    if not messages or not issue_type:
        return jsonify({"error": "messages and issue_type are required"}), 400

    if chat_id is None:
        chat_id = next_chat_id(DB_PATH)

    try:
        chat_data = process_single_chat(
            chat_id=chat_id,
            messages=messages,
            issue_type=issue_type,
            persona=persona,
            db_path=DB_PATH,
            dry_run=dry_run,
        )
        return jsonify({"status": "ok", "chat": chat_data}), 200

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route("/chat/<int:chat_id>", methods=["GET"])
def get_chat(chat_id: int) -> Any:
    with ChatDatabase(DB_PATH) as db:
        chat = db.get_chat_with_features(chat_id)
        if chat is None:
            return jsonify({"error": "Chat not found"}), 404
        return jsonify({"status": "ok", "chat": chat}), 200


@app.route("/simulate", methods=["POST"])
def simulate_chat() -> Any:
    """Generate a simulated chat and process it end-to-end."""
    payload = request.get_json(force=True) or {}
    issue_type = payload.get("issue_type")
    persona = payload.get("persona")
    dry_run = payload.get("dry_run", False)

    simulator = ChatSimulator()
    conversation, issue, persona = simulator.generate_conversation(issue_type=issue_type, persona=persona)

    # Only keep user turns for processing; bot responses will be generated by the LLM.
    messages = [
        {"role": "user", "content": msg}
        for role, msg in conversation
        if role == "customer"
    ]

    chat_id = next_chat_id(DB_PATH)
    chat_data = process_single_chat(
        chat_id=chat_id,
        messages=messages,
        issue_type=issue,
        persona=persona,
        db_path=DB_PATH,
        dry_run=dry_run,
    )

    return jsonify({"status": "ok", "chat": chat_data}), 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
